/*
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.native.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Result of performing a Tor node check on an IP address
 */
@ApiModel(description = "Result of performing a Tor node check on an IP address")
@JsonPropertyOrder({
  ThreatDetectionTorNodeResponse.JSON_PROPERTY_IS_TOR_NODE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-15T17:34:21.930465900-07:00[America/Los_Angeles]")
public class ThreatDetectionTorNodeResponse {
  public static final String JSON_PROPERTY_IS_TOR_NODE = "IsTorNode";
  private Boolean isTorNode;

  public ThreatDetectionTorNodeResponse() { 
  }

  public ThreatDetectionTorNodeResponse isTorNode(Boolean isTorNode) {
    this.isTorNode = isTorNode;
    return this;
  }

   /**
   * True if the input IP address is a Tor exit node, false otherwise
   * @return isTorNode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True if the input IP address is a Tor exit node, false otherwise")
  @JsonProperty(JSON_PROPERTY_IS_TOR_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsTorNode() {
    return isTorNode;
  }


  @JsonProperty(JSON_PROPERTY_IS_TOR_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsTorNode(Boolean isTorNode) {
    this.isTorNode = isTorNode;
  }


  /**
   * Return true if this ThreatDetectionTorNodeResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreatDetectionTorNodeResponse threatDetectionTorNodeResponse = (ThreatDetectionTorNodeResponse) o;
    return Objects.equals(this.isTorNode, threatDetectionTorNodeResponse.isTorNode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isTorNode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreatDetectionTorNodeResponse {\n");
    sb.append("    isTorNode: ").append(toIndentedString(isTorNode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

