/*
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.ntv.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ThreatDetectionBotCheckResponse
 */
public class ThreatDetectionBotCheckResponseTest {
    private final ThreatDetectionBotCheckResponse model = new ThreatDetectionBotCheckResponse();

    /**
     * Model tests for ThreatDetectionBotCheckResponse
     */
    @Test
    public void testThreatDetectionBotCheckResponse() {
        // TODO: test ThreatDetectionBotCheckResponse
    }

    /**
     * Test the property 'isBot'
     */
    @Test
    public void isBotTest() {
        // TODO: test isBot
    }

}
