/*
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.native;

import com.cloudmersive.client.native.invoker.ApiException;
import com.cloudmersive.client.native.model.CreateSettingRequest;
import com.cloudmersive.client.native.model.CreateSettingResponse;
import com.cloudmersive.client.native.model.ListSettingsRequest;
import com.cloudmersive.client.native.model.ListSettingsResponse;
import com.cloudmersive.client.native.model.UpdateSettingRequest;
import com.cloudmersive.client.native.model.UpdateSettingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for SettingsApi
 */
@Ignore
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    
    /**
     * Create a setting in the specified bucket
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsCreateSettingTest() throws ApiException {
        CreateSettingRequest request = null;
        CreateSettingResponse response = 
        api.settingsCreateSetting(request);
        
        // TODO: test validations
    }
    
    /**
     * Enumerate the settings in a bucket
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsListSettingsTest() throws ApiException {
        ListSettingsRequest request = null;
        ListSettingsResponse response = 
        api.settingsListSettings(request);
        
        // TODO: test validations
    }
    
    /**
     * Update a setting
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void settingsUpdateSettingTest() throws ApiException {
        UpdateSettingRequest request = null;
        UpdateSettingResponse response = 
        api.settingsUpdateSetting(request);
        
        // TODO: test validations
    }
    
}
