/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.native;

import com.cloudmersive.client.native.invoker.ApiException;
import com.cloudmersive.client.native.model.DocumentTransformEditSession;
import com.cloudmersive.client.native.model.DocxTableTableFillMultiRequest;
import com.cloudmersive.client.native.model.DocxTableTableFillRequest;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for TransformDocumentApi
 */
@Ignore
public class TransformDocumentApiTest {

    private final TransformDocumentApi api = new TransformDocumentApi();

    
    /**
     * Replace string in Word DOCX document, return result
     *
     * Replace all instances of a string in an Office Word Document (docx)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformDocumentDocxReplaceTest() throws ApiException {
        String matchString = null;
        String replaceString = null;
        String inputFileUrl = null;
        Boolean matchCase = null;
        File inputFile = null;
        byte[] response = 
        api.transformDocumentDocxReplace(matchString, replaceString, inputFileUrl, matchCase, inputFile);
        
        // TODO: test validations
    }
    
    /**
     * Replace string in Word DOCX document, return edit session
     *
     * Replace all instances of a string in an Office Word Document (docx).  Returns an edit session URL so that you can chain together multiple edit operations without having to send the entire document contents back and forth multiple times.  Call the Finish Editing API to retrieve the final document once editing is complete.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformDocumentDocxReplaceEditSessionTest() throws ApiException {
        String matchString = null;
        String replaceString = null;
        String inputFileUrl = null;
        Boolean matchCase = null;
        File inputFile = null;
        DocumentTransformEditSession response = 
        api.transformDocumentDocxReplaceEditSession(matchString, replaceString, inputFileUrl, matchCase, inputFile);
        
        // TODO: test validations
    }
    
    /**
     * Fill in data in a table in a Word DOCX document, return result
     *
     * Replace placeholder rows ina  table in an Office Word Document (docx) using one or more templates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformDocumentDocxTableFillInTest() throws ApiException {
        DocxTableTableFillRequest request = null;
        byte[] response = 
        api.transformDocumentDocxTableFillIn(request);
        
        // TODO: test validations
    }
    
    /**
     * Fill in data in a table in a Word DOCX document, return edit session
     *
     * Replace placeholder rows ina  table in an Office Word Document (docx) using one or more templates.  Returns an edit session URL so that you can chain together multiple edit operations without having to send the entire document contents back and forth multiple times.  Call the Finish Editing API to retrieve the final document once editing is complete.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformDocumentDocxTableFillInEditSessionTest() throws ApiException {
        DocxTableTableFillRequest request = null;
        DocumentTransformEditSession response = 
        api.transformDocumentDocxTableFillInEditSession(request);
        
        // TODO: test validations
    }
    
    /**
     * Fill in data in multiple tables in a Word DOCX document, return result
     *
     * Replace placeholder rows in multiple tables in an Office Word Document (docx) using one or more templates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformDocumentDocxTableFillInMultiTest() throws ApiException {
        DocxTableTableFillMultiRequest request = null;
        byte[] response = 
        api.transformDocumentDocxTableFillInMulti(request);
        
        // TODO: test validations
    }
    
    /**
     * Replace string in PowerPoint PPTX presentation, return result
     *
     * Replace all instances of a string in an Office PowerPoint Document (pptx)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transformDocumentPptxReplaceTest() throws ApiException {
        String matchString = null;
        String replaceString = null;
        String inputFileUrl = null;
        Boolean matchCase = null;
        File inputFile = null;
        byte[] response = 
        api.transformDocumentPptxReplace(matchString, replaceString, inputFileUrl, matchCase, inputFile);
        
        // TODO: test validations
    }
    
}
