/*
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.native.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IPThreatDetectionResponse
 */
public class IPThreatDetectionResponseTest {
    private final IPThreatDetectionResponse model = new IPThreatDetectionResponse();

    /**
     * Model tests for IPThreatDetectionResponse
     */
    @Test
    public void testIPThreatDetectionResponse() {
        // TODO: test IPThreatDetectionResponse
    }

    /**
     * Test the property 'isThreat'
     */
    @Test
    public void isThreatTest() {
        // TODO: test isThreat
    }

    /**
     * Test the property 'threatType'
     */
    @Test
    public void threatTypeTest() {
        // TODO: test threatType
    }

}
