/*
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.native.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StringXssProtectionResult
 */
public class StringXssProtectionResultTest {
    private final StringXssProtectionResult model = new StringXssProtectionResult();

    /**
     * Model tests for StringXssProtectionResult
     */
    @Test
    public void testStringXssProtectionResult() {
        // TODO: test StringXssProtectionResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'containedXss'
     */
    @Test
    public void containedXssTest() {
        // TODO: test containedXss
    }

    /**
     * Test the property 'originalInput'
     */
    @Test
    public void originalInputTest() {
        // TODO: test originalInput
    }

    /**
     * Test the property 'normalizedResult'
     */
    @Test
    public void normalizedResultTest() {
        // TODO: test normalizedResult
    }

}
