/*
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.native.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StringAutomaticThreatDetection
 */
public class StringAutomaticThreatDetectionTest {
    private final StringAutomaticThreatDetection model = new StringAutomaticThreatDetection();

    /**
     * Model tests for StringAutomaticThreatDetection
     */
    @Test
    public void testStringAutomaticThreatDetection() {
        // TODO: test StringAutomaticThreatDetection
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'cleanResult'
     */
    @Test
    public void cleanResultTest() {
        // TODO: test cleanResult
    }

    /**
     * Test the property 'containedJsonInsecureDeserializationAttack'
     */
    @Test
    public void containedJsonInsecureDeserializationAttackTest() {
        // TODO: test containedJsonInsecureDeserializationAttack
    }

    /**
     * Test the property 'containedXssThreat'
     */
    @Test
    public void containedXssThreatTest() {
        // TODO: test containedXssThreat
    }

    /**
     * Test the property 'containedXxeThreat'
     */
    @Test
    public void containedXxeThreatTest() {
        // TODO: test containedXxeThreat
    }

    /**
     * Test the property 'containedSqlInjectionThreat'
     */
    @Test
    public void containedSqlInjectionThreatTest() {
        // TODO: test containedSqlInjectionThreat
    }

    /**
     * Test the property 'containedSsrfThreat'
     */
    @Test
    public void containedSsrfThreatTest() {
        // TODO: test containedSsrfThreat
    }

    /**
     * Test the property 'isXML'
     */
    @Test
    public void isXMLTest() {
        // TODO: test isXML
    }

    /**
     * Test the property 'isJSON'
     */
    @Test
    public void isJSONTest() {
        // TODO: test isJSON
    }

    /**
     * Test the property 'isURL'
     */
    @Test
    public void isURLTest() {
        // TODO: test isURL
    }

    /**
     * Test the property 'originalInput'
     */
    @Test
    public void originalInputTest() {
        // TODO: test originalInput
    }

}
