/*
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cloudmersive.client.native;

import com.cloudmersive.client.native.invoker.ApiClient;
import com.cloudmersive.client.native.invoker.ApiException;
import com.cloudmersive.client.native.invoker.ApiResponse;
import com.cloudmersive.client.native.invoker.Pair;

import java.math.BigDecimal;
import java.io.File;
import com.cloudmersive.client.native.model.MediaInformation;
import com.cloudmersive.client.native.model.NsfwResult;
import java.time.OffsetDateTime;
import com.cloudmersive.client.native.model.SplitVideoResult;
import com.cloudmersive.client.native.model.StillFramesResult;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-15T17:34:05.331264-07:00[America/Los_Angeles]")
public class VideoApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public VideoApi() {
    this(new ApiClient());
  }

  public VideoApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Convert Video to Animated GIF format.
   * Automatically detect video file format and convert it to animated GIF format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB. Default height is 250 pixels, while preserving the video&#39;s aspect ratio.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to 250 pixels, maximum is 500 pixels. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to 250 pixels, maximum is 500 pixels. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to 24 frames per second. (optional)
   * @param startTime Optional; Specify the desired starting time of the GIF video in TimeSpan format. (optional)
   * @param timeSpan Optional; Specify the desired length of the GIF video in TimeSpan format. Limit is 30 seconds. Default is 10 seconds. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoConvertToGif(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, OffsetDateTime startTime, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoConvertToGifWithHttpInfo(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, startTime, timeSpan, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Convert Video to Animated GIF format.
   * Automatically detect video file format and convert it to animated GIF format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB. Default height is 250 pixels, while preserving the video&#39;s aspect ratio.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to 250 pixels, maximum is 500 pixels. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to 250 pixels, maximum is 500 pixels. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to 24 frames per second. (optional)
   * @param startTime Optional; Specify the desired starting time of the GIF video in TimeSpan format. (optional)
   * @param timeSpan Optional; Specify the desired length of the GIF video in TimeSpan format. Limit is 30 seconds. Default is 10 seconds. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoConvertToGifWithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, OffsetDateTime startTime, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoConvertToGifRequestBuilder(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, startTime, timeSpan, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoConvertToGif", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoConvertToGifRequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, OffsetDateTime startTime, OffsetDateTime timeSpan, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/convert/to/gif";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (preserveAspectRatio != null) {
      localVarRequestBuilder.header("preserveAspectRatio", preserveAspectRatio.toString());
    }
    if (frameRate != null) {
      localVarRequestBuilder.header("frameRate", frameRate.toString());
    }
    if (startTime != null) {
      localVarRequestBuilder.header("startTime", startTime.toString());
    }
    if (timeSpan != null) {
      localVarRequestBuilder.header("timeSpan", timeSpan.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Convert Video to MOV format.
   * Automatically detect video file format and convert it to MOV format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoConvertToMov(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoConvertToMovWithHttpInfo(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, quality, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Convert Video to MOV format.
   * Automatically detect video file format and convert it to MOV format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoConvertToMovWithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoConvertToMovRequestBuilder(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, quality, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoConvertToMov", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoConvertToMovRequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/convert/to/mov";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (preserveAspectRatio != null) {
      localVarRequestBuilder.header("preserveAspectRatio", preserveAspectRatio.toString());
    }
    if (frameRate != null) {
      localVarRequestBuilder.header("frameRate", frameRate.toString());
    }
    if (quality != null) {
      localVarRequestBuilder.header("quality", quality.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Convert Video to MP4 format.
   * Automatically detect video file format and convert it to MP4 format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoConvertToMp4(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoConvertToMp4WithHttpInfo(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, quality, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Convert Video to MP4 format.
   * Automatically detect video file format and convert it to MP4 format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoConvertToMp4WithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoConvertToMp4RequestBuilder(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, quality, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoConvertToMp4", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoConvertToMp4RequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/convert/to/mp4";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (preserveAspectRatio != null) {
      localVarRequestBuilder.header("preserveAspectRatio", preserveAspectRatio.toString());
    }
    if (frameRate != null) {
      localVarRequestBuilder.header("frameRate", frameRate.toString());
    }
    if (quality != null) {
      localVarRequestBuilder.header("quality", quality.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Convert Video to PNG Still Frames.
   * Automatically detect video file format and convert it to an array of still frame PNG images. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param framesPerSecond Optional; How many video frames per second to be returned as PNG images. Minimum value is 0.1, maximum is 60. Default is 1 frame per second. Maximum of 2000 total frames. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return StillFramesResult
   * @throws ApiException if fails to make API call
   */
  public StillFramesResult videoConvertToStillFrames(String fileUrl, Integer maxWidth, Integer maxHeight, BigDecimal framesPerSecond, File inputFile) throws ApiException {
    ApiResponse<StillFramesResult> localVarResponse = videoConvertToStillFramesWithHttpInfo(fileUrl, maxWidth, maxHeight, framesPerSecond, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Convert Video to PNG Still Frames.
   * Automatically detect video file format and convert it to an array of still frame PNG images. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param framesPerSecond Optional; How many video frames per second to be returned as PNG images. Minimum value is 0.1, maximum is 60. Default is 1 frame per second. Maximum of 2000 total frames. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;StillFramesResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<StillFramesResult> videoConvertToStillFramesWithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, BigDecimal framesPerSecond, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoConvertToStillFramesRequestBuilder(fileUrl, maxWidth, maxHeight, framesPerSecond, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoConvertToStillFrames", localVarResponse);
        }
        return new ApiResponse<StillFramesResult>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<StillFramesResult>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoConvertToStillFramesRequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, BigDecimal framesPerSecond, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/convert/to/still-frames";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (framesPerSecond != null) {
      localVarRequestBuilder.header("framesPerSecond", framesPerSecond.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json, text/json, application/xml, text/xml");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Convert Video to WEBM format.
   * Automatically detect video file format and convert it to WEBM format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoConvertToWebm(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoConvertToWebmWithHttpInfo(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, quality, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Convert Video to WEBM format.
   * Automatically detect video file format and convert it to WEBM format. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param preserveAspectRatio Optional; If false, the original video&#39;s aspect ratio will not be preserved, allowing customization of the aspect ratio using maxWidth and maxHeight, potentially skewing the video. Default is true. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoConvertToWebmWithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoConvertToWebmRequestBuilder(fileUrl, maxWidth, maxHeight, preserveAspectRatio, frameRate, quality, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoConvertToWebm", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoConvertToWebmRequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, Boolean preserveAspectRatio, Integer frameRate, Integer quality, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/convert/to/webm";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (preserveAspectRatio != null) {
      localVarRequestBuilder.header("preserveAspectRatio", preserveAspectRatio.toString());
    }
    if (frameRate != null) {
      localVarRequestBuilder.header("frameRate", frameRate.toString());
    }
    if (quality != null) {
      localVarRequestBuilder.header("quality", quality.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Cut a Video to a Shorter Length
   * Cuts a video to the specified start and end times. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param startTime Optional; Specify the desired starting time of the cut video in TimeSpan format. (optional)
   * @param timeSpan Optional; Specify the desired length of the cut video in TimeSpan format. Leave blank to include the rest of the video. Maximum time is 4 hours. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoCutVideo(String fileUrl, OffsetDateTime startTime, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoCutVideoWithHttpInfo(fileUrl, startTime, timeSpan, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Cut a Video to a Shorter Length
   * Cuts a video to the specified start and end times. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param startTime Optional; Specify the desired starting time of the cut video in TimeSpan format. (optional)
   * @param timeSpan Optional; Specify the desired length of the cut video in TimeSpan format. Leave blank to include the rest of the video. Maximum time is 4 hours. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoCutVideoWithHttpInfo(String fileUrl, OffsetDateTime startTime, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoCutVideoRequestBuilder(fileUrl, startTime, timeSpan, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoCutVideo", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoCutVideoRequestBuilder(String fileUrl, OffsetDateTime startTime, OffsetDateTime timeSpan, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/cut";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (startTime != null) {
      localVarRequestBuilder.header("startTime", startTime.toString());
    }
    if (timeSpan != null) {
      localVarRequestBuilder.header("timeSpan", timeSpan.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Get detailed information about a video or audio file
   * Retrieve detailed information about a video or audio file, including format, dimensions, file size, bit rate, duration and start time. Compatible with many formats, including: AVI, ASF, FLV, GIF, MP4, MPEG/MPG, Matroska/WEBM, MOV, AIFF, ASF, CAF, MP3, MP2, MP1, Ogg, OMG/OMA, and WAV. Uses 1 API call per 10 MB of file size.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return MediaInformation
   * @throws ApiException if fails to make API call
   */
  public MediaInformation videoGetInfo(String fileUrl, File inputFile) throws ApiException {
    ApiResponse<MediaInformation> localVarResponse = videoGetInfoWithHttpInfo(fileUrl, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Get detailed information about a video or audio file
   * Retrieve detailed information about a video or audio file, including format, dimensions, file size, bit rate, duration and start time. Compatible with many formats, including: AVI, ASF, FLV, GIF, MP4, MPEG/MPG, Matroska/WEBM, MOV, AIFF, ASF, CAF, MP3, MP2, MP1, Ogg, OMG/OMA, and WAV. Uses 1 API call per 10 MB of file size.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;MediaInformation&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MediaInformation> videoGetInfoWithHttpInfo(String fileUrl, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoGetInfoRequestBuilder(fileUrl, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoGetInfo", localVarResponse);
        }
        return new ApiResponse<MediaInformation>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<MediaInformation>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoGetInfoRequestBuilder(String fileUrl, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/convert/get-info";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json, text/json, application/xml, text/xml");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Resizes a Video Preserving the Original Aspect Ratio.
   * Resizes a video, while maintaining the original aspect ratio and encoding. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param extension Optional; Specify the file extension of the input video. This is recommended when inputting a file directly, without a file name. If no file name is available and no extension is provided, the extension will be inferred from the file data, which may cause a different extension to be used in the output. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoResizeVideo(String fileUrl, Integer maxWidth, Integer maxHeight, Integer frameRate, Integer quality, String extension, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoResizeVideoWithHttpInfo(fileUrl, maxWidth, maxHeight, frameRate, quality, extension, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Resizes a Video Preserving the Original Aspect Ratio.
   * Resizes a video, while maintaining the original aspect ratio and encoding. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param extension Optional; Specify the file extension of the input video. This is recommended when inputting a file directly, without a file name. If no file name is available and no extension is provided, the extension will be inferred from the file data, which may cause a different extension to be used in the output. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoResizeVideoWithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, Integer frameRate, Integer quality, String extension, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoResizeVideoRequestBuilder(fileUrl, maxWidth, maxHeight, frameRate, quality, extension, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoResizeVideo", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoResizeVideoRequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, Integer frameRate, Integer quality, String extension, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/resize/preserveAspectRatio";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (frameRate != null) {
      localVarRequestBuilder.header("frameRate", frameRate.toString());
    }
    if (quality != null) {
      localVarRequestBuilder.header("quality", quality.toString());
    }
    if (extension != null) {
      localVarRequestBuilder.header("extension", extension.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Resizes a Video without Preserving Aspect Ratio.
   * Resizes a video without maintaining original aspect ratio, allowing fully customizable dimensions. May cause image skewing. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param extension Optional; Specify the file extension of the input video. This is recommended when inputting a file directly, without a file name. If no file name is available and no extension is provided, the extension will be inferred from the file data, which may cause a different extension to be used in the output. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return byte[]
   * @throws ApiException if fails to make API call
   */
  public byte[] videoResizeVideoSimple(String fileUrl, Integer maxWidth, Integer maxHeight, Integer frameRate, Integer quality, String extension, File inputFile) throws ApiException {
    ApiResponse<byte[]> localVarResponse = videoResizeVideoSimpleWithHttpInfo(fileUrl, maxWidth, maxHeight, frameRate, quality, extension, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Resizes a Video without Preserving Aspect Ratio.
   * Resizes a video without maintaining original aspect ratio, allowing fully customizable dimensions. May cause image skewing. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param maxWidth Optional; Maximum width of the output video, up to the original video width. Defaults to original video width. (optional)
   * @param maxHeight Optional; Maximum height of the output video, up to the original video width. Defaults to original video height. (optional)
   * @param frameRate Optional; Specify the frame rate of the output video. Defaults to original video frame rate. (optional)
   * @param quality Optional; Specify the quality of the output video, where 100 is lossless and 1 is the lowest possible quality with highest compression. Default is 50. (optional)
   * @param extension Optional; Specify the file extension of the input video. This is recommended when inputting a file directly, without a file name. If no file name is available and no extension is provided, the extension will be inferred from the file data, which may cause a different extension to be used in the output. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;byte[]&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<byte[]> videoResizeVideoSimpleWithHttpInfo(String fileUrl, Integer maxWidth, Integer maxHeight, Integer frameRate, Integer quality, String extension, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoResizeVideoSimpleRequestBuilder(fileUrl, maxWidth, maxHeight, frameRate, quality, extension, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoResizeVideoSimple", localVarResponse);
        }
        return new ApiResponse<byte[]>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<byte[]>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoResizeVideoSimpleRequestBuilder(String fileUrl, Integer maxWidth, Integer maxHeight, Integer frameRate, Integer quality, String extension, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/resize/target";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (maxWidth != null) {
      localVarRequestBuilder.header("maxWidth", maxWidth.toString());
    }
    if (maxHeight != null) {
      localVarRequestBuilder.header("maxHeight", maxHeight.toString());
    }
    if (frameRate != null) {
      localVarRequestBuilder.header("frameRate", frameRate.toString());
    }
    if (quality != null) {
      localVarRequestBuilder.header("quality", quality.toString());
    }
    if (extension != null) {
      localVarRequestBuilder.header("extension", extension.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Scan a Video for NSFW content.
   * Automatically detect video file format and scan it for Not Safe For Work (NSFW)/Porn/Racy content. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per frame scanned.
   * @param fileUrl Optional; URL of a video file being scanned. Use this option for files larger than 2GB. (optional)
   * @param framesPerSecond Optional; How many video frames per second to be scanned. Minimum value is 0.05 (1 frame per 20 seconds), maximum is 1. Default is 0.33 frame per second (1 frame scanned every 3 seconds). Maximum of 1000 total frames can be scanned, potentially adjusting the framerate for longer videos. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return NsfwResult
   * @throws ApiException if fails to make API call
   */
  public NsfwResult videoScanForNsfw(String fileUrl, BigDecimal framesPerSecond, File inputFile) throws ApiException {
    ApiResponse<NsfwResult> localVarResponse = videoScanForNsfwWithHttpInfo(fileUrl, framesPerSecond, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Scan a Video for NSFW content.
   * Automatically detect video file format and scan it for Not Safe For Work (NSFW)/Porn/Racy content. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, OGV, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per frame scanned.
   * @param fileUrl Optional; URL of a video file being scanned. Use this option for files larger than 2GB. (optional)
   * @param framesPerSecond Optional; How many video frames per second to be scanned. Minimum value is 0.05 (1 frame per 20 seconds), maximum is 1. Default is 0.33 frame per second (1 frame scanned every 3 seconds). Maximum of 1000 total frames can be scanned, potentially adjusting the framerate for longer videos. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;NsfwResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NsfwResult> videoScanForNsfwWithHttpInfo(String fileUrl, BigDecimal framesPerSecond, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoScanForNsfwRequestBuilder(fileUrl, framesPerSecond, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoScanForNsfw", localVarResponse);
        }
        return new ApiResponse<NsfwResult>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<NsfwResult>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoScanForNsfwRequestBuilder(String fileUrl, BigDecimal framesPerSecond, File inputFile) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/scan/nsfw";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (framesPerSecond != null) {
      localVarRequestBuilder.header("framesPerSecond", framesPerSecond.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json, text/json, application/xml, text/xml");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * Split a Video into Two Shorter Videos
   * Cuts a video into two videos based on the specified start time. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param splitTime Specify the desired time at which to split the video in TimeSpan format. (required)
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param timeSpan Optional; Specify the desired length of the second video in TimeSpan format. Leave blank to include the rest of the video. Maximum time is 4 hours. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return SplitVideoResult
   * @throws ApiException if fails to make API call
   */
  public SplitVideoResult videoSplitVideo(OffsetDateTime splitTime, String fileUrl, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    ApiResponse<SplitVideoResult> localVarResponse = videoSplitVideoWithHttpInfo(splitTime, fileUrl, timeSpan, inputFile);
    return localVarResponse.getData();
  }

  /**
   * Split a Video into Two Shorter Videos
   * Cuts a video into two videos based on the specified start time. Supports many input video formats, including AVI, ASF, FLV, MP4, MPEG/MPG, Matroska/WEBM, 3G2, MKV, M4V and MOV. Uses 1 API call per 10 MB of file size. Also uses 1 API call per additional minute of processing time over 5 minutes, up to a maximum of 25 minutes total processing time. Maximum output file size is 50GB.
   * @param splitTime Specify the desired time at which to split the video in TimeSpan format. (required)
   * @param fileUrl Optional; URL of a video file being used for conversion. Use this option for files larger than 2GB. (optional)
   * @param timeSpan Optional; Specify the desired length of the second video in TimeSpan format. Leave blank to include the rest of the video. Maximum time is 4 hours. (optional)
   * @param inputFile Input file to perform the operation on. (optional)
   * @return ApiResponse&lt;SplitVideoResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SplitVideoResult> videoSplitVideoWithHttpInfo(OffsetDateTime splitTime, String fileUrl, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = videoSplitVideoRequestBuilder(splitTime, fileUrl, timeSpan, inputFile);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("videoSplitVideo", localVarResponse);
        }
        return new ApiResponse<SplitVideoResult>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<SplitVideoResult>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder videoSplitVideoRequestBuilder(OffsetDateTime splitTime, String fileUrl, OffsetDateTime timeSpan, File inputFile) throws ApiException {
    // verify the required parameter 'splitTime' is set
    if (splitTime == null) {
      throw new ApiException(400, "Missing the required parameter 'splitTime' when calling videoSplitVideo");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/video/split";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (fileUrl != null) {
      localVarRequestBuilder.header("fileUrl", fileUrl.toString());
    }
    if (splitTime != null) {
      localVarRequestBuilder.header("splitTime", splitTime.toString());
    }
    if (timeSpan != null) {
      localVarRequestBuilder.header("timeSpan", timeSpan.toString());
    }
    localVarRequestBuilder.header("Accept", "application/octet-stream");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
